✅ tests: enforce coverage in pre-commit

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -1,4 +1,3 @@
-
 # if --cov is passed, then we want to run the coverage command
 if [ "$1" = "--cov" ]; then
 
@@ -8,12 +7,30 @@ if [ "$1" = "--cov" ]; then
 
     # if -v or --verbose is passed, then we want to print the coverage report
     if [ "$2" = "-v" ] || [ "$2" = "--verbose" ]; then
-        cargo llvm-cov --release --ignore-filename-regex=$regex --show-missing-lines --fail-under-lines 80 -- test_
-        exit 0
+        cargo llvm-cov --release --ignore-filename-regex=$regex --show-missing-lines --fail-under-lines 100 --cobertura --output-path coverage.xml -- test_
+    else
+        cargo llvm-cov --release --ignore-filename-regex=$regex --fail-under-lines 100 --cobertura --output-path coverage.xml -- test_
     fi
 
-    cargo llvm-cov --release --ignore-filename-regex=$regex --fail-under-lines 80 -- test_
-    exit 0
-fi
+    # Search for the first instance of line-rate="{float}"
+    match=$(grep -o 'line-rate="[0-9.]\+"' coverage.xml | head -n 1)
 
-cargo test --release -- test_
+    # Check if a match was found
+    if [ -n "$match" ]; then
+        # Extract the float value from the match
+        float=$(echo "$match" | grep -o '[0-9.]\+')
+
+        # Compare the float value with 0.5
+        if (( $(awk 'BEGIN {print ('$float' < 0.6)}') )); then
+            echo "coverage of $float is less than 0.6"
+            exit 1
+        else
+            exit 0
+        fi
+    else
+        echo "coverage.xml not found"
+        exit 1
+    fi
+else
+    cargo test --release -- test_
+fi
